### PR TITLE
Fixed smallvec implementations to process elements inside.

### LINKED ISSUE #89: Remove `'static` bound from `T` for `ToBoundedStatic for smallvec::SmallVec<[T; N]>`

### PR DESCRIPTION
**Pull request by xkikeg**
Now there's one drawback that in some case SmallVec<A> won't be supported where A is still smallvec::Array but isn't [T; N]. However, it should be OK in reality, given smallvec itself is going to be SmallVec<T, N> instead of SmallVec<[T; N]> with removing this.

Context: https://github.com/servo/rust-smallvec/issues/183

Closes #89

### CODE REVIEW

**Comment by fujiapple852** [comment]
Hi @xkikeg and thanks for another PR!

So as I understand it:

- `smallvec` 1.x is defined as `SmallVec<A: Array>` where `Array` is a trait with an `Item` associated type
- `smallvec` 2.x is defined as `SmallVec<T, const N: usize>`

This PR improves the impl from:

```
impl<A> ToBoundedStatic for smallvec::SmallVec<A> 
where
    A: smallvec::Array + 'static,
    A::Item: Clone
``` 

To become:

```
impl<T, const N: usize> ToBoundedStatic for smallvec::SmallVec<[T; N]>
where
    [T; N]: smallvec::Array<Item = T>,
    [T::Static; N]: smallvec::Array<Item = T::Static>,
    T: ToBoundedStatic
```

This is clearly an improvement, as we can now convert any `SmallVec<[T; N]>` where `T: ToBoundedStatic`.

The limitation, as you note, is that it is restricting the usage to `SmallVec<[T; N]>` rather than the more general `SmallVec<A>` where `A: Array`.  Not an issue for `smallvec` 2.x but could be a limitation for `smallvec` 1.x users.

I had a try and generalising it for the current `smallvec` 1.x version and came up with this (and similar for `IntoBoundedStatic`):

```
impl<A, T> ToBoundedStatic for smallvec::SmallVec<A>
where
    A: smallvec::Array<Item = T> + ToBoundedStatic,
    T: ToBoundedStatic,
    <A as ToBoundedStatic>::Static: smallvec::Array<Item = T::Static>,
{
    type Static = smallvec::SmallVec<A::Static>;

    fn to_static(&self) -> Self::Static {
        self.iter().map(ToBoundedStatic::to_static).collect()
    }
}
```

To make this work I also had to remove the `Copy` restriction from `impl<T, const N: usize> ToBoundedStatic for [T; N]` which is possible these days thanks to `core::array::from_fn`.

I changed:

```
impl<T, const N: usize> ToBoundedStatic for [T; N]
where
    T: ToBoundedStatic + Copy,
{
    type Static = [T::Static; N];

    fn to_static(&self) -> Self::Static {
        // Note that we required that `T` is `Copy` here whereas the `IntoBoundedStatic` impl does not.
        self.map(|item| item.to_static())
    }
}
```

To become:

```
impl<T, const N: usize> ToBoundedStatic for [T; N]
where
    T: ToBoundedStatic,
{
    type Static = [T::Static; N];

    fn to_static(&self) -> Self::Static {
        core::array::from_fn(|i| self[i].to_static())
    }
}
```

What do you think?

File: bounded-static/src/lib.rs [hunk 1]
```diff
@@ -1706,6 +1709,23 @@ mod smallvec_tests {
         ensure_static(small_vec.to_static());
         ensure_static(small_vec.into_static());
     }
+
+    #[cfg(feature = "alloc")]
+    mod alloc_smallvec_tests {
```
Comment (fujiapple852) [inline bounded-static/src/lib.rs:1714]: nit: it is probably overkill to have a module for this, annotating the test directly is fine since there is only one.

Comment (xkikeg) [reply bounded-static/src/lib.rs:1714]: Thanks, I'm still not familiar with Rust full ecosystem, so that's nicer if it works.

**Comment by xkikeg** [comment]
Thanks for suggestions! Your impl seems good so no objections for going with that approach (A: Array<Item=T>).

**Comment by fujiapple852** [comment]
@xkikeg merged, thanks.  Do you need this immediately?  If not i'd prefer to hold off on a release until some other changes land.
